"""make status_code in check_logs nullable

Revision ID: 4aae7c041f40
Revises: 79442881c079
Create Date: 2026-05-07 12:32:02.495387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4aae7c041f40"
down_revision: str | Sequence[str] | None = "79442881c079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "check_logs", "status_code", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "check_logs", "status_code", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
