"""Add new columns to monitors

Revision ID: e17974d1c973
Revises: d2ae86683076
Create Date: 2026-04-30 14:52:58.952009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e17974d1c973"
down_revision: str | Sequence[str] | None = "d2ae86683076"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitors",
        sa.Column(
            "timeout", sa.Integer(), server_default=sa.text("10"), nullable=False
        ),
    )
    op.add_column(
        "monitors", sa.Column("last_status_code", sa.Integer(), nullable=True)
    )
    op.add_column(
        "monitors",
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "monitors",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_monitors_user_id_users"), "monitors", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_monitors_user_id_users"),
        "monitors",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_monitors_user_id_users"), "monitors", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_monitors_user_id_users"), "monitors", "users", ["user_id"], ["id"]
    )
    op.drop_column("monitors", "updated_at")
    op.drop_column("monitors", "last_checked_at")
    op.drop_column("monitors", "last_status_code")
    op.drop_column("monitors", "timeout")
    # ### end Alembic commands ###
