"""Rename columns, add cascade delete

Revision ID: fb2ad52a15a2
Revises: e17974d1c973
Create Date: 2026-05-03 18:16:23.367716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb2ad52a15a2"
down_revision: str | Sequence[str] | None = "e17974d1c973"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_checklogs_monitor_id_monitors"), "checklogs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_checklogs_monitor_id_monitors"),
        "checklogs",
        "monitors",
        ["monitor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "incidents", sa.Column("started_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "incidents", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(
        op.f("fk_incidents_monitor_id_monitors"), "incidents", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_incidents_monitor_id_monitors"),
        "incidents",
        "monitors",
        ["monitor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("incidents", "end_at")
    op.drop_column("incidents", "start_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incidents",
        sa.Column(
            "start_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "end_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("fk_incidents_monitor_id_monitors"), "incidents", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_incidents_monitor_id_monitors"),
        "incidents",
        "monitors",
        ["monitor_id"],
        ["id"],
    )
    op.drop_column("incidents", "ended_at")
    op.drop_column("incidents", "started_at")
    op.drop_constraint(
        op.f("fk_checklogs_monitor_id_monitors"), "checklogs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_checklogs_monitor_id_monitors"),
        "checklogs",
        "monitors",
        ["monitor_id"],
        ["id"],
    )
    # ### end Alembic commands ###
